### ISSUE TITLE
issue on color

### ISSUE THREAD

**Issue by a2zunicon** [amadii69/github-crash-course#1]
It looks more better if the main title h1 is a bite orange

the sytling rule could be changed like this:-

```css
h1 {
  color: #ec9f1a;
}
```
